# Generated by Django 6.0.5 on 2026-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "data_gb",
                    models.PositiveIntegerField(help_text="Included data in GB"),
                ),
                (
                    "voice_minutes",
                    models.PositiveIntegerField(help_text="Included voice minutes"),
                ),
                ("sms_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
