# Generated by Django 6.0.5 on 2026-05-29 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
